service:
  name: cvs-svc-stum-crm-atfs

openapi: 3.0.0

plugins:
  - serverless-offline
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs8.10

custom:
  serverless-offline:
    port: 3004
  documentation:
    version: '1'
    title: 'List of Test Stations'
    description: 'This is the API spec for retrieving the list of Test Stations'
    models:
      - name: "Test Station"
        description: "Get Test Stations successful response"
        contentType: "application/json"
        schema:
          type: "array"
          items:
            type: "object"
            properties:
              testStationId:
                type: "string"
              testStationPNumber:
                type: "string"
              testStationName:
                type: string
              testStationContactNumber:
                type: string
              testStationAccessNotes:
                type: string
              testStationGeneralNotes:
                type: string
              testStationTown:
                type: string
              testStationAddress:
                type: string
              testStationPostcode:
                type: string
              testStationLongitude:
                type: number
              testStationLatitude:
                type: number
              testStationType:
                type: "atf"
              testStationEmails: [
                "string"
              ]

functions:
  getATFs:
    handler: src/handler.handler
    events:
      - http:
          path: "test-stations"
          method: "get"
          documentation:
            summary: "Get Test Station List"
            description: "Returns all existing Test Stations from the database"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "List of Test Stations"
                responseModels:
                  "application/json": "Test Stations"
              - statusCode: 500
                responseBody:
                  description: "The error trace"
                responseModels:
                  content:
                    application/json:
                      schema:
                        type: array
                        items:
                          type: string
