service:
  name: cvs-svc-stum-crm-test-station

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getTestStations:
    handler: src/handler.handler
    events:
      - http:
          path: "test-stations"
          method: "get"  

custom:
  serverless-offline:
    port: 3004
  dynamodb:
    start:
      port: 8007
      inMemory: true
      migrate: true
      seed: false
      noStart: true
    seed:
      test-stations:
        sources:
          - table: cvs-local-test-stations
            sources: [./tests/resources/test-stations.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-stations
        AttributeDefinitions:
        - AttributeName: testStationId
          AttributeType: S
        KeySchema:
        - AttributeName: testStationId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
