service:
  name: cvs-svc-stum-crm-test-station

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs8.10
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  getTestStations:
    handler: src/handler.handler
    events:
      - http:
          path: "test-stations"
          method: "get"

custom:
  serverless-offline:
    port: 3004
  dynamodb:
    start:
      port: 8007
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      test-stations:
        sources:
          - table: cvs-local-test-stations
            sources: [./tests/resources/test-stations.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-stations
        AttributeDefinitions:
        - AttributeName: testStationId
          AttributeType: S
        KeySchema:
        - AttributeName: testStationId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
