openapi: 3.0.0
components:
  schemas:
    Test Station:
      type: array
      items:
        type: object
        properties:
          testStationId:
            type: string
          testStationPNumber:
            type: string
          testStationName:
            type: string
          testStationContactNumber:
            type: string
          testStationAccessNotes:
            type: string
          testStationGeneralNotes:
            type: string
          testStationTown:
            type: string
          testStationAddress:
            type: string
          testStationPostcode:
            type: string
          testStationLongitude:
            type: number
          testStationLatitude:
            type: number
          testStationType:
            type: atf
          testStationEmails:
            - string
  securitySchemes: {}
info:
  title: List of Test Stations
  description: This is the API spec for retrieving the list of Test Stations
  version: '1'
paths:
  /test-stations:
    get:
      operationId: getATFs
      summary: Get Test Station List
      description: Returns all existing Test Stations from the database
      responses:
        '200':
          description: List of Test Stations
          content: {}
        '500':
          description: The error trace
          content: {}
